### ISSUE TITLE
Crash on Galaxy S7 (Android 7.0)

### ISSUE THREAD

**Issue by RadAd** [RadAd/RadUnread#1]
java.lang.RuntimeException: Unable to create service au.radsoft.unread.UpdateService: java.lang.SecurityException: Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps?notify=true from pid=24109, uid=10236 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1740)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.SecurityException: Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps?notify=true from pid=24109, uid=10236 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1693)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
	at android.content.ContentResolver.insert(ContentResolver.java:1280)
	at au.radsoft.unread.badger.SamsungHomeBadger.executeBadge(SamsungHomeBadger.java:58)
	at au.radsoft.unread.ShortcutBadger.setBadge(ShortcutBadger.java:61)
	at au.radsoft.unread.ShortcutBadger.setBadge(ShortcutBadger.java:56)
	at au.radsoft.unread.GmailObserver.updateUnread(GmailObserver.java:67)
	at au.radsoft.unread.UpdateService.onSharedPreferenceChanged(UpdateService.java:85)
	at au.radsoft.unread.UpdateService.onCreate(UpdateService.java:45)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3522)
	... 8 more

**Comment by RadAd** [comment]
The permission com.sec.android.provider.badge.permission.WRITE is already in the AndroidManifest.xml. Currently building with API level android-21.
